# Generated by Django 3.2.7 on 2021-12-06 10:11

from django.conf import settings
from django.db import migrations, models
import event_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=event_api.models.upload_to, verbose_name='Image')),
                ('categories', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10)),
                ('published', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('dislike', models.ManyToManyField(blank=True, null=True, related_name='dislike', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, editable=False, null=True, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
