# Generated by Django 3.2.7 on 2021-12-06 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dislike',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
